[2024-03-06T18:43:22.458+0000] {scheduler_job_runner.py:1575} WARNING - Marking task instance <TaskInstance: webscrapper.fetch_html_page manual__2024-03-06T18:33:03.326387+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
[2024-03-06T18:43:22.679+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: webscrapper.fetch_html_page manual__2024-03-06T18:33:03.326387+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
